#!/bin/bash
#Provide function name after CDK deployment:
fn="LambdaLayerStack-LambdaFunctionBF21E41F-XzRF7ZvYq6Kj"
echo "Deleting previous test results..."
rm response*.json
echo "Executing tests"
aws lambda invoke --function-name $fn --cli-binary-format raw-in-base64-out --payload '{"word":"function", "context":"In Javascript a function can be run asynchronously"}' --output json response1.json &
aws lambda invoke --function-name $fn --cli-binary-format raw-in-base64-out --payload '{"word":"function", "context":"the promotion required to more responsabilities in his job function"}' --output json response2.json &
aws lambda invoke --function-name $fn --cli-binary-format raw-in-base64-out --payload '{"word":"function", "context":"the engine ran out of fuel and stopped to function"}' --output json response3.json &
aws lambda invoke --function-name $fn --cli-binary-format raw-in-base64-out --payload '{"word":"function", "context":"the math teacher started wrote a function on the blackboard"}' --output json response4.json &